# Generated by Django 3.2 on 2021-04-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='templates/images/back.jpg', upload_to='templates/images/'),
        ),
    ]
