# Generated by Django 3.2 on 2021-04-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='templates/image/back.jpg', upload_to='templates/image/'),
        ),
    ]
